import { parseNetwork, type ParseNetworkParams } from "./utils";

const chainWithPrivateRpcs: ParseNetworkParams[] = [
  "ancient8",
  "apechain",
  "appchain",
  "arbitrum",
  "avalanche",
  "b3",
  "base",
  "blast",
  "bob",
  "celo",
  "corn",
  "cyber",
  "degen",
  "ethereum",
  "forma",
  "funki",
  "gnosis",
  "hemi",
  "ink",
  "linea",
  "lisk",
  "mantle",
  "metis",
  "mint",
  "mode",
  "optimism",
  "perennial",
  "plume",
  "polygon",
  "rari",
  "redstone",
  "ronin",
  "sanko",
  "scroll",
  "sei",
  "shape",
  "solana",
  "soneium",
  "sonic",
  "stable",
  "story",
  "superposition",
  "superseed",
  "unichain",
  "worldchain",
  "xai",
  "zero",
  "zircuit",
  "zksync",
  "zora",
].map((slug) => ({ slug, httpRpcUrl: "private" }));

const chainsWithDefaultRpcs: ParseNetworkParams[] = [
  "cronos",
  "morph",
  "abstract",
  "polygon_zkevm",
  "hyperevm",
  "manta",
  "boba",
  "bnb",
  "katana",
  "ethereal",
  "anime",
  "syndicate",
  "tron",
  "flow",
  "swellchain",
  "somnia",
  "gravity",
  "powerloom",
  "arena_z",
  "plasma",
  "taiko",
  "berachain",
  "eclipse",
  "gunz",
  "soon",
].map((slug) => ({ slug }));

module.exports = [
  ...chainWithPrivateRpcs,
  ...chainsWithDefaultRpcs,
  {
    slug: "hyperliquid",
    httpRpcUrl: "https://api.hyperliquid.xyz",
    additionalData: {
      hubApiUrl: "http://relay-protocol-hub.platform.svc.cluster.local",
    },
  },
  {
    slug: "arbitrum_nova",
    httpRpcUrl:
      "http://proxy-arbitrum-nova.nodes.svc.cluster.local:8545/arbitrumnova",
  },
  {
    slug: "megaeth",
    httpRpcUrl:
      "https://alpha.megaeth.com/rpc?user=relay+v1&token=1763427813-qx5yROYcmgsnXf6tFi%2FP1MLyfjlkqLFZBC06tZXNdbA%3D",
  },
  {
    slug: "monad",
    httpRpcUrl:
      "https://rpc-mainnet.monadinfra.com/rpc/dELACPvISYPJenyJNHoQ36qhdMXH9dPl",
  },
  {
    slug: "bitcoin",
    additionalData: {
      esploraCompatibleApiUrl: "https://enterprise.blockstream.info/api",
    },
  },
].map((chain) => parseNetwork({ ...chain, env: "prod" }));
